# -*- coding: utf-8 -*-
source 'https://rubygems.org'
ruby '2.2.0'
require 'erb'
require 'yaml'

gem 'sinatra'
gem 'rake'
gem 'redis'
gem 'redis-namespace'
gem 'redis-objects'
gem 'mysql2'
gem 'gcm'
gem 'minitest'
gem 'json'
gem 'activerecord'
gem 'sinatra-activerecord'